import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    padding: 20,
    flexDirection: "row",
    flex: 1,
  },
  avatar: {
    height: 30,
    aspectRatio: 1,
    borderRadius: 15,
  },
  containerOther: {
    padding: 20,
    flexDirection: "row-reverse",
    flex: 1,
  },
  containerText: {
    marginHorizontal: 10,
    backgroundColor: "rgb(209, 209, 209)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  containerTextOther: {
    marginHorizontal: 10,
    backgroundColor: "#90e4c1",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  Text: {
    color: "red",
  },
  TextOther: {
    color: "red",
  },
  containerTabText: {
    marginTop: 10,
    marginLeft: 10,
    marginRight: -13,
    backgroundColor: "rgb(209, 209, 209)",
    paddingVertical: 4,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    width: 10,
    zIndex: 5,
    marginBottom: 1,
  },
  containerTabOver: {
    marginTop: 10,
    marginLeft: 10,
    marginRight: -17,
    marginBottom: 2,
    backgroundColor: "white",
    paddingVertical: 4,
    borderBottomRightRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    width: 10,
    zIndex: 6,
  },
  containerTabTextOther: {
    marginTop: 10,
    marginRight: 10,
    marginLeft: -13,
    backgroundColor: "#90e4c1",
    paddingVertical: 4,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    width: 10,
    zIndex: 5,
    marginBottom: 1,
  },
  containerTabOverOther: {
    marginTop: 10,
    marginRight: 10,
    marginLeft: -17,
    marginBottom: 2,
    backgroundColor: "white",
    paddingVertical: 4,
    borderBottomLeftRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    width: 10,
    zIndex: 6,
  },
});

export default styles;
