export const BUTTON_WIDTH = 320;
export const BUTTON_HEIGHT = 60;
export const BUTTON_PADDING = 5;
export const SWIPABLE_DIMENSIONS = BUTTON_HEIGHT - 2 * BUTTON_PADDING;

export const H_WAVE_RANGE = SWIPABLE_DIMENSIONS + 2 * BUTTON_PADDING;
export const H_SWIPE_RANGE =
  BUTTON_WIDTH - 2 * BUTTON_PADDING - SWIPABLE_DIMENSIONS;
