import { StyleSheet } from "react-native";
import {
  BUTTON_WIDTH,
  BUTTON_HEIGHT,
  BUTTON_PADDING,
  SWIPABLE_DIMENSIONS,
} from "./const";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 30,
    backgroundColor: "#EAEAEA",
  },
  outerContainer: {
    marginBottom: 10,
  },
  formContainer: {
    marginHorizontal: 20,
    flexDirection: "row",
    backgroundColor: "white",
    padding: 10,
    borderRadius: 10,
  },
  greyTitle: {
    marginHorizontal: 40,
    marginTop: 20,
    marginBottom: 10,
    color: "#888888",
    fontSize: 12,
  },
  inputText: {
    marginRight: 20,
    flex: 1,
  },
  inputNumber: {
    marginHorizontal: 10,
    paddingRight: 20,
    // backgroundColor: "red",
    flex: 1,
  },
  mediaPreview: {
    aspectRatio: 9 / 16,
    backgroundColor: "black",
    width: 60,
    borderRadius: 5,
  },
  buttonsContainer: {
    flexDirection: "row",
    marginHorizontal: 20,
    paddingVertical: 20,
    alignContent: "center",
    marginTop: "auto",
    marginVertical: 20,
  },
  prefixText: {
    alignSelf: "center",
  },
  postButton: {
    alignItems: "center",
    flexDirection: "row",
    flex: 1,
    backgroundColor: "#ff4040",
    paddingVertical: 10,
    paddingHorizontal: 20,
    justifyContent: "center",
    height: "20px",
    borderRadius: 4,
    marginBottom: 20,
  },
  cancelButtonText: {
    fontWeight: "bold",
    color: "black",
    fontSize: 16,
    marginLeft: 5,
  },
  postButtonText: {
    fontWeight: "bold",
    color: "white",
    fontSize: 16,
    marginLeft: 5,
  },
  uploadContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  SwipeContainer: {
    height: BUTTON_HEIGHT,
    width: BUTTON_WIDTH,
    padding: BUTTON_PADDING,
    backgroundColor: "rgba(144, 228, 193, 1)",
    marginHorizontal: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    marginBottom: 50,
    marginTop: 20,
  },
  swipeable: {
    height: SWIPABLE_DIMENSIONS,
    width: SWIPABLE_DIMENSIONS,
    borderRadius: 20,
    position: "absolute",
    left: 5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
  },
  swipeText: {
    color: "white",
    alignSelf: "center",
    fontSize: 14,
    zIndex: 2,
  },
  swipeAfterText: {
    color: "rgba(100, 180, 150, 1)",
    fontSize: 14,
    zIndex: 2,
    fontWeight: "bold",
    width: 110,
  },
  colorWave: {
    position: "absolute",
    left: 0,
    height: BUTTON_HEIGHT,
    borderRadius: 20,
    display: "flex",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.5)",
  },
});

export default styles;
